spring.application.name=${SPRING_APPLICATION_NAME:video-service}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:2GB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:2GB}
server.port=${SERVER_PORT:8082}
aws.access-key=${AWS_ACCESS_KEY:AWSAKIA46OOQAM4TK5KH67O}
aws.secret-key=${AWS_SECRET_KEY:dtmSJQwsyoJXr8BCt0z3vMqlheUlwMlx8JtnFAHe}
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:netflix-streaming-videos-890028163897-us-east-1-an}
management.endpoints.web.exposure.include=health,info


